# Generated by Django 3.2.4 on 2023-02-12 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_plan',
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contact', to='users.customuser'),
            preserve_default=False,
        ),
    ]
