# Generated by Django 3.2.4 on 2023-02-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_plan', to='users.userplan'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='users.contact'),
        ),
    ]
