# Generated by Django 3.2.4 on 2023-02-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230217_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.userplan'),
        ),
    ]
