# Generated by Django 3.2.4 on 2023-01-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230127_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tg_user_id',
        ),
    ]
