# Generated by Django 3.2.4 on 2023-01-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='chat_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tg_user_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
