# Generated by Django 4.1.5 on 2023-01-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='chat_id',
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tg_user_id',
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
    ]
