# Generated by Django 3.2.4 on 2023-01-31 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_auto_20230131_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='domains.contactplan'),
        ),
    ]
