# Generated by Django 3.2.4 on 2023-01-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_contactplan_contactplanfeature_domain_paymenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tg_user_id',
        ),
    ]
